server:
  port: 8080



# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root   #你本地的数据库用户名
    password: 1932245341 #你本地的数据库密码
    url: jdbc:mysql://localhost:3306/iyouyangshuo?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true

  data:
    redis:
      host: localhost
      port: 6379
      password: 1932245341
      database: 11

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

iyouyangshuo:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: d2VsbCBhbGxvd2VkIGZyb20gdGhlIHN0b3JtIGp1c3QgbG9uZyByZXBvcnRzIGF
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: 4vEPzY5X4b8e3wKZqsdfgdfafsdasdasafsd
    user-ttl: 7200000
    user-token-name: authorization
    marketer-secret-key: 4asdjfklfdasjdffsdfdsgfsgzY5Xasdasafsd
    marketer-ttl: 7200000
    marketer-token-name: marketer

  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tHmMEhovCWpMmNkZKmY
    access-key-secret: 78xgZfX80zH7khGiOJo4jYvUX1luww
    bucket-name: iyouyangshuo


  wechat:
    appid: wx84dc7360e14c600d
    secret: 3d8de18f0ff56d7e9080b15bb766fadf
    mchid:  # 微信支付商户号
    mchSerialNo:  # 微信支付商户证书序列号
    privateKeyFilePath:  # 微信支付商户私钥文件路径
    apiV3Key:  # 微信支付API v3密钥
    weChatPayCertFilePath:  # 微信支付证书文件路径
    notifyUrl:  # 微信支付通知URL
    refundNotifyUrl:  # 微信支付退款通知URL

# 配置swagger文档的访问路径，访问地址：http://127.0.0.1:8080/swagger-ui.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

alipay:
  appId: 9021000145620328
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCxAbap+UlaSHUNMkgtqdSPkvJyqjdEfrz7EiIvaO7sLPnTE0VAHTsexcqwjEE94+i6VdRPC+QtDAel14qLW4+zqudzqarA9xx9gwD0gppCi52jlMBqoqoFGAqC7BCDeKCaaxqIV6S1czHW/0D9hKac7cdCxEvMuIYPPwFW0JXz8xY4twCDxN0ERxj7cvAiieXz3/aXVfb6Y5BgBS5cwJUvVT3opwUKbP+SUeHmpQQkUrSeg2FFQhZZK8UMPCaMa6cHi+O/xs2zARDqBaTXsnlhx6kDQu1bcxUG6eCAx8iwsVDNr3n7ZhC665u1LZUmmw+p8cJz8/4VWWJvrA+VQ4uPAgMBAAECggEAMMRQFzRfSUh9N02LJUmNDqFlusG6yFxCpMmyMW2vpdIeYlEE200yZKAJ3+pEb1DDZdMP01drXh3aXY6s1Qg85ztG2U79hHyQlOPq93KkHYFpxQ/Ok5KNVSnye2+efRpW5TRs8vNypas/KATbWv2ZCdNY+sQqPhT4mmq5a7m8FqGEdQ/aIWU4U3+7y8dQ83LvdENF5Ic7sojgIk8Sfttoa08ACudC58z5XYkyumSZrhF3qnzEhsBLrckpHD7dpYMzV/kBUvQFo+vh5QDjmqgzAWDhcaH4hvOQ3/qoeXhzxHSIEGPSQddFH1px7YdSFLy/Wxga8SEeqeYtpsyukwvKQQKBgQDvwwiTTjTDivAlP4R3mZCD7F5J8Tc67tyO6m+kdLyDWxNAWP6bbZe9TOHDHVoBkWVc5ej098eblp67NnHwsQViBk3UDLGyo+Q8kthRzNRb4zF7kBw3AHPpTtT08dzvMbefBILJ/+1hzD+I+eBt6OS4vc+ONgoYr5G95LRJPxZsowKBgQC8/qM1f/qUwbQyhY6PS1RO/D0inRY5d8iHB1iswdJJT+YupawSvhF4kPFOttB0Ew15Wiu7/Y8Wogr0qVPhojipHTJcNImytXxAMe8or0eiLeLtGi18uPfM9YIHSfEgiziUyu8scUxZUOd9WfcRvwiDujv6t8mvtG2W+YYpBShIJQKBgQDduODvSH1m78+QwqJ/79VDCo1Pl/BZYZc52vcPgJzsZIbzFNmvZrPSbYzB4RzhIlI4jKzYDWPcMHft7TWFPk8aDXZfyLVz3DgvBCVj0CX6K6oQ+H3/Jz4J3cr2Ec0crj9+oK9KmpAtxrJiu6GeQqdxaKbOfo7rsUD3+M34hoz4PQKBgQCqEj8OYsc82/7rQ9Jg0nngxg3BuziHqGn0UMEUXSp9vH+31HA/QXj5VP1BRzPYcFi8rk8S0X7U8CcJueJ49gEk9dger0yGW9ie8BB2PR0qLT66/MaYKN8dOoSzSG/LSF03UFLgXGhHK43U+INkHdNsrsdQu9ir26KOrKZ0/WYdXQKBgEQMC6RsS45xa7ouO8n/joQZGTKzZ6hxdCuvSYk83sYYHbFb/eeFlkTkHOsQEVYZHnZIjTaNLIiU8Kht289iJe/Ur/ooc1CnFvK6wPEeJmcAJ6saGIPtkbEe5r4/i5ut/YU+TDdCkF9feOMqGx69zGR4E6b5Mz2GfGQleqn1PxxZ
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj/2FUIG1RPidrH29twCZBjp7wgEyKdE/PJcIPtV0k1cL0yRc/+fYCVDic2KEdHlT1h5cPhAYHchCySlIVk+iRzRDmahV4gpNYLoTAeq4VmNT5YjOlsJ+yGf7ttSZBUbHSVVXwTkvYYFMhVa3jGw9hSI5ltBXpfGs8Ml9hohTirNk6P3Pr17RpRmDSO8BKhB39jPlgxlaBuMMDC2jFn6fsc59aEOd5gEWQrbfoVKqfsrwWMphomo1vqBpqPtH/hPNC3Rh3AzZNYdYMjqesYletBJUxMwwZWL5jm6ACMBCTYAVpqP4c5d3cm2e6NBVpp0jK9yE8oCHbi3FcOMnFCPfmQIDAQAB
  notifyUrl: http://kb88ad.natappfree.cc/alipay/notify

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  pageSizeZero: true





